=== Nuke4/XML/target/classes/medicine.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/Medicines"
        xmlns:tns="http://www.example.com/Medicines">

        <element name="medicines">
            <complexType>
                <sequence>
                    <element name="medicine" type="tns:Medicine" minOccurs="1"
                                maxOccurs="unbounded" />
                </sequence>
            </complexType>
        </element>
        <complexType name="Medicine">
            <sequence>
                <element name="price" type="int" />
                <element name="dosage" type="int" />
                <element name="visual" type="tns:Visual" />
            </sequence>
            <attribute name="name" type="tns:Name" use="required"/>
        </complexType>

        <simpleType name="Name">
            <restriction base="ID">
                <pattern value="[a-zA-Z]{3}[a-zA-Z0-9_]*"/>
            </restriction>
        </simpleType>

        <complexType name="Visual">
            <sequence>
                <element name="color" type="string"></element>
                <element name="consistency" type="string"></element>
                <element name="indications" type="string"></element>
            </sequence>
        </complexType>
</schema>

=== Nuke4/XML/src/main/resources/medicine.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:medicines xmlns:tns="http://www.example.com/Medicines"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://www.example.com/Medicines medicine.xsd ">
    <medicine name="citramon">
        <price>20</price>
        <dosage>5</dosage>
        <visual>
            <color>Белый</color>
            <consistency>Твёрдый</consistency>
            <indications>Головные боли</indications>
        </visual>
    </medicine>
    <medicine name="tempalgin">
        <price>100</price>
        <dosage>5</dosage>
        <visual>
            <color>Серый</color>
            <consistency>Твёрдый</consistency>
            <indications>Зубная боль</indications>
        </visual>
    </medicine>
    <medicine name="ambroksan">
        <price>300</price>
        <dosage>100</dosage>
        <visual>
            <color>Зелёный</color>
            <consistency>Жидкий</consistency>
            <indications>Респираторные заболевания</indications>
        </visual>
    </medicine>
    <medicine name="ultramorin">
        <price>500</price>
        <dosage>10</dosage>
        <visual>
            <color>Красный</color>
            <consistency>Твёрдый</consistency>
            <indications>Психические заболевания</indications>
        </visual>
    </medicine>
</tns:medicines>
